[colors]
p = "#ffd4e3"
s = "#ffb5cf"

[messages]
broadcast = """
    <p>{player} was <s>{action}</s> by <s>{punisher}</s>
"""
banScreen = """
    You have been banned!
    Reason: {reason}
"""
kickScreen = """
    You have been kicked!
    Reason: {reason}
"""
muted = """
     You are muted
     Reason: {reason}
     Expires: {expiry}
"""

[messages.clearchat]
alertAll = "<p>The chat has been <s>cleared"
alertSelf = "<p>You've cleared the chat for others, but you're immune!"
alertStaff = "<p>The chat has been cleared by <s>{player}</s>, but you're immune!"

[messages.mutechat]
invalidAction = "Chat is already {state}"
alertAll = "<p>The chat has been <s>{state}"

mutedAlertSelf = "<p>You've <s>muted</s> the chat, but you can still talk!"
mutedAlertStaff = "<p>Chat has been <s>muted</s> by <s>{player}</s>, but you can still talk!"

unmutedAlertSelf = "<p>You've <s>unmuted</s> the chat"
unmutedAlertStaff = "<p>Chat has been <s>unmuted</s> by <s>{player}</s>"

[messages.general]
errorPrefix = "<#ff6e6e>⚠<#ff7f6e>"
reloadConfig = "<p>Silhouette has been reloaded!"
noPlayerFound = "Couldn't find a player called {player} ;c"
chatMuted = "The chat is currently muted ;c"