# Here you can define custom minimessage color codes to use in any message/etc Usage: <color-code>Text text</color-code>
[colors]
# Primary, secondary and tertiary are mandatory color codes.
# These are used in the plugin by default, you may change them for a quick color scheme switch, but you shouldn't remove
# them, even if you aren't using them in any of the messages defined here. This is because they're used in
# non-configurable messages (like /silhouette info). Again, you can change their color to your liking.
p = "#ffd4e3" # Primary
s = "#ffb5cf" # Secondary
t = "#6b5569" # Tertiary
# Define extra color codes here: eg:
purpley = "#e0b8ff" # -> <purpley>Some message</purpley>

# Similar to custom color codes, you can set custom placeholders to use in any message/etc. Usage "hi {placeholder}."
[custom_placeholders]
error = "<#ff6e6e>⚠<#ff7f6e>"

[messages]
broadcast = """
    <p>{target} was <s>{action}</s> by <s>{punisher}</s>
"""
banScreen = """
    You have been banned!
    Reason: {reason}
"""
kickScreen = """
    You have been kicked!
    Reason: {reason}
"""
muted = """
     You are muted
     Reason: {reason}
     Expires: {expiry}
"""
reloadConfig = "<p>Silhouette has been reloaded!"

[messages.errors]
noPlayerFound = "{error} Couldn't find a player called {target} ;c"
noExistingPunishment = "{error} {target} is not currently {existing-action}! ;c"
chatMuted = "{error} The chat is currently muted ;c"
noHistory = "{error} No history found for {target} on page {page} ;c"
noType = "{error} You chose an invalid type! ;c"

[messages.clearchat]
alertAll = "<p>The chat has been <s>cleared"
alertSelf = "<p>You've cleared the chat for others, but you're immune!"
alertStaff = "<p>The chat has been cleared by <s>{target}</s>, but you're immune!"

[messages.mutechat]
invalidAction = "{error} Chat is already {state}"
alertAll = "<p>The chat has been <s>{state}"

mutedAlertSelf = "<p>You've <s>muted</s> the chat, but you can still talk!"
mutedAlertStaff = "<p>Chat has been <s>muted</s> by <s>{target}</s>, but you can still talk!"

unmutedAlertSelf = "<p>You've <s>unmuted</s> the chat"
unmutedAlertStaff = "<p>Chat has been <s>unmuted</s> by <s>{target}</s>"

[messages.gui.history]
title = "{target}s history"
itemName = "<p>{type_2} for <s>{reason}"
itemLore = """
    <p>Issued: <s>{happenedAt}</s>
    <p>{expiry_tag}: <s>{expiry_date}</s>
    <p>Punisher: <s>{punisher}</s>

    <#baa5d4> • <#f0c9ff>Left Click: <#ac99c4>Edit {type} reason
"""
typeLore = """
<p>Manage different types of punishments.

{type_selector}
"""

historyType = " <#baa5d4>• <#f0c9ff>{item}: <#ac99c4>{description}"
selectedHistoryType = " <#baa5d4>➜ <#f0c9ff>{item}: <#ac99c4>{description}"
[messages.gui.editPunishment]
title = "Edit Punishment"
successfulEdit = "<p>Updated punishment reason to <s>{reason}"

# As a punishment is being typed, eg: "/kick UwUAroze 7d KillAur-", the player, duration, reason, and flags will be pre-parsed and displayed in the actionbar.
# This proves useful as a way to ensure the punishment is correct before executing it.
[actionbars.punishment_preparse]
base = "<p>{action} <s>{target}</s> <b>|</b> Reason: <s>{reason}</s>{p_duration}{p_flags}" # This actionbar will show up to moderators typing a punish command | Placeholders: {action}, {p_duration}, {p_flags}, {reason}, {target}
p_duration = " <b>|</b> Duration: <s>{duration}</s>" # Extra placeholder to format duration, ie: "1 day and 12 hours", only prsent if the punishment supports durations, otherwise blank | Placeholders: {duration}
p_flags = " <b>|</b> Flags: <s>{flags}</s>" # Extra placeholder to format flags, ie: "silent", only present if one or more flags are present, otherwise blank | Placeholders: {flags}
noPlayer = "<p>{action} <b>|</b> <s>Specify a player!</s>" # This actionbar will show when a player is not specified in a command, eg: when typing "/kick " | Placeholders: {action}